import Header from "./components/Header";
import Footer from "./components/Footer";
import MyApp from "./_app";
import Head from "next/head";
import { SpeedInsights } from "@vercel/speed-insights/next";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const previewImageURL = "https://emelie.org/page-preview.png";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta property="og:image" content={previewImageURL} />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Rouge+Script&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <MyApp>
          <Header />
          {children}
          <Footer />
        </MyApp>
        <SpeedInsights />
      </body>
    </html>
  );
}
